### ISSUE TITLE
Add other vigilance states

### ISSUE THREAD

**Issue by Fefedefe** [giuseb/fabermat#3]
I think it would be useful to add a state for SoREM and a state for the epochs in which more than 50% of the time (10 s) is occupied by artifacts. We could call this state UNSCORED o FOURH STATE.

**Comment by giuseb** [comment]
You can start scoring with an arbitrary number of states described by arbitrary labels:

``` matlab
>> sleeper(eeg, emg, 'States', {'REM', 'nREM', 'Wake', 'SoREM', 'Art'})
```

What I still need to implement is automatic mapping of states to number keys, depending on how many states you need; right now sleeper accepts exactly four states.
